// android/test/launcher.test.js — checks for the Android wrapper in android/.
//
// Run directly (it is intentionally NOT under the game repository's test/, so `node --test` at the repo root does
// not pick it up):  node android/test/launcher.test.js
//
// The launcher page (android/web/launcher.js) is a plain classic script loaded by the WebView, so it cannot be
// imported as a module here. Its address parser is therefore extracted from the source text and exercised
// directly — that parser decides which URL the WebView navigates to, so getting it wrong means nobody can join.
//
// Also checked:
//   * every file android/web/index.html references exists (or is generated by android/scripts/assemble-nodejs.mjs);
//   * capacitor.config.json keeps the settings the wrapper depends on: the CapacitorNodeJS plugin in manual mode
//     with nodeDir "nodejs", and server.allowNavigation — without it Capacitor hands a LAN address to the system
//     browser instead of loading it in the WebView.
//
// The wrapper is optional (it needs the Android SDK and the game art), so everything skips cleanly when absent.

import { test, describe } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// android/test/ -> android/ (the Capacitor project root) -> the game repository root
const APP = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const ROOT = path.resolve(APP, '..');
const WEB = path.join(APP, 'web');
const LAUNCHER = path.join(WEB, 'launcher.js');
const CONFIG = path.join(APP, 'capacitor.config.json');

const exists = existsSync(LAUNCHER);
const skip = exists ? false : 'android/web/launcher.js not present';

/** Extract a top-level `function name(...) { ... }` definition by brace matching. */
function extractFunction(source, name) {
  const start = source.indexOf(`function ${name}(`);
  if (start < 0) throw new Error(`function ${name} not found`);
  const open = source.indexOf('{', start);
  if (open < 0) throw new Error(`no body for ${name}`);
  let depth = 0;
  for (let i = open; i < source.length; i++) {
    const ch = source[i];
    if (ch === '{') depth++;
    else if (ch === '}') {
      depth--;
      if (depth === 0) return source.slice(start, i + 1);
    }
  }
  throw new Error(`unbalanced braces for ${name}`);
}

describe('android launcher: address parsing', { skip }, () => {
  const source = readFileSync(LAUNCHER, 'utf8');
  // The function closes over DEFAULT_PORT, so bind it the same way the page does.
  const DEFAULT_PORT = 3000;
  const normaliseAddress = new Function(
    'DEFAULT_PORT',
    `${extractFunction(source, 'normaliseAddress')}\nreturn normaliseAddress;`,
  )(DEFAULT_PORT);

  const CASES = [
    // A bare host (what a player types when reading the address off the host's screen) gets http + :3000.
    ['192.168.1.23', 'http://192.168.1.23:3000/'],
    ['192.168.1.23:3000', 'http://192.168.1.23:3000/'],
    ['http://192.168.1.23', 'http://192.168.1.23:3000/'],
    ['http://192.168.1.23:3000/', 'http://192.168.1.23:3000/'],
    ['  10.0.0.5:3001  ', 'http://10.0.0.5:3001/'],
    // The hostname/port must survive so the game client's own absolute URLs (/data/, /ws) still resolve.
    ['example.com:8080', 'http://example.com:8080/'],
    // ?room= is what makes "复制链接" work; it has to be preserved (and left percent-encoded).
    ['192.168.1.23:3000/?room=ABCD', 'http://192.168.1.23:3000/?room=ABCD'],
    ['http://192.168.1.23:3000/?room=abcd', 'http://192.168.1.23:3000/?room=abcd'],
    // An explicit https host (a tunnel / reverse proxy) keeps its scheme and its implicit 443.
    ['https://game.example.com/?room=XY12', 'https://game.example.com/?room=XY12'],
    ['https://game.example.com', 'https://game.example.com/'],
    ['https://game.example.com:8443', 'https://game.example.com:8443/'],
    // Rejections: empty input and anything that is not http(s).
    ['', null],
    ['   ', null],
    ['ftp://192.168.1.23/a', null],
    ['file:///etc/passwd', null],
  ];

  for (const [input, expected] of CASES) {
    test(`${JSON.stringify(input)} → ${JSON.stringify(expected)}`, () => {
      assert.equal(normaliseAddress(input), expected);
    });
  }
});

describe('android launcher: referenced files exist', { skip }, () => {
  test('index.html references resolve to a committed file or an assembled one', () => {
    const html = readFileSync(path.join(WEB, 'index.html'), 'utf8');
    const refs = [...html.matchAll(/(?:src|href)="\.\/([^"]+)"/g)].map((m) => m[1]);
    assert.ok(refs.length >= 4, `expected several local references, got ${refs.length}`);
    // vendor/ is produced by android/scripts/assemble-nodejs.mjs from node_modules, so it may legitimately be
    // absent in a fresh checkout; the committed files must always be there.
    const generated = (r) => r.startsWith('vendor/');
    for (const ref of refs) {
      if (generated(ref)) continue;
      assert.ok(existsSync(path.join(WEB, ref)), `index.html references missing file: ${ref}`);
    }
    assert.ok(refs.includes('launcher.js'), 'index.html must load launcher.js');
    assert.ok(refs.includes('launcher.css'), 'index.html must load launcher.css');
    assert.ok(refs.includes('vendor/capacitor.js'), 'index.html must load the Capacitor core bundle');
    assert.ok(refs.includes('vendor/capacitor-nodejs.js'), 'index.html must load the Node.js plugin bundle');
  });
});

describe('android launcher: capacitor config', { skip }, () => {
  const config = exists ? JSON.parse(readFileSync(CONFIG, 'utf8')) : {};

  test('the Node.js plugin runs in manual mode out of web/nodejs', () => {
    const plugin = config.plugins?.CapacitorNodeJS;
    assert.ok(plugin, 'plugins.CapacitorNodeJS is required');
    assert.equal(plugin.nodeDir, 'nodejs');
    assert.equal(plugin.startMode, 'manual', 'manual mode is required so the launcher can show progress');
    assert.equal(config.webDir, 'web');
  });

  test('allowNavigation is set, or Capacitor would open LAN addresses in the system browser', () => {
    const allow = config.server?.allowNavigation;
    assert.ok(Array.isArray(allow) && allow.length > 0, 'server.allowNavigation must not be empty');
    assert.ok(allow.includes('*'), 'the LAN host is only known at runtime, so "*" is required');
  });

  test('cleartext traffic is allowed for the plain-http LAN server', () => {
    const manifest = path.join(APP, 'android', 'app', 'src', 'main', 'AndroidManifest.xml');
    if (!existsSync(manifest)) return; // native project not added yet
    const xml = readFileSync(manifest, 'utf8');
    assert.match(xml, /android:usesCleartextTraffic="true"/, 'the LAN server is plain http');
    assert.match(xml, /android\.permission\.INTERNET/, 'sockets need the INTERNET permission');
  });
});

// ---------------------------------------------------------------------------------------------------
// LAN discovery plumbing. Two phones that both tapped 「建立主机」 are two independent authoritative servers
// (server/lobby.js keeps rooms in a process-local Map), so the only way they end up in one match is for one of them
// to find the other and join. That is four pieces that have to line up, and none of them fails loudly if it is
// missing — the list is just always empty — so each one is asserted here.
// ---------------------------------------------------------------------------------------------------
describe('android launcher: LAN discovery wiring', { skip }, () => {
  const source = readFileSync(LAUNCHER, 'utf8');
  const html = readFileSync(path.join(WEB, 'index.html'), 'utf8');
  const native = path.join(APP, 'android', 'app', 'src', 'main', 'java', 'io', 'github', 'sganggs', 'strongholdprotocol');

  test('the page has somewhere to put the discovered rooms', () => {
    for (const id of ['card-lan', 'host-list', 'discover-state', 'btn-rescan', 'host-rival']) {
      assert.ok(html.includes(`id="${id}"`), `index.html is missing #${id}`);
    }
  });

  test('launcher.js looks the plugin up by the exact name the native side registers', () => {
    const pluginName = /registerPlugin\('([A-Za-z]+)'\)/.exec(source)?.[1];
    assert.equal(pluginName, 'LanDiscovery');
    const annotation = path.join(native, 'lan', 'LanDiscoveryPlugin.java');
    if (!existsSync(annotation)) return;
    assert.match(readFileSync(annotation, 'utf8'), /@CapacitorPlugin\(name = "LanDiscovery"\)/);
  });

  test('MainActivity registers the plugin before super.onCreate()', () => {
    const activity = path.join(native, 'MainActivity.java');
    if (!existsSync(activity)) return;
    const java = readFileSync(activity, 'utf8');
    const register = java.indexOf('registerPlugin(LanDiscoveryPlugin.class)');
    const superCall = java.indexOf('super.onCreate(savedInstanceState)');
    assert.ok(register > 0, 'MainActivity must register LanDiscoveryPlugin');
    assert.ok(superCall > 0 && register < superCall, 'BridgeActivity builds the Bridge inside its own onCreate, so a later registerPlugin is unreachable from JS');
  });

  test('the launcher polls rather than waiting for an event, and stops again before navigating away', () => {
    assert.match(source, /LanDiscovery\.getHosts\(\)/);
    assert.match(source, /LanDiscovery\.stop\(\)/);
    assert.match(source, /await stopDiscovery\(\);/, 'enterGame() must stop the native seeker before leaving the page');
  });

  test('a host seen over several interfaces becomes a single row', () => {
    // We broadcast `who` on every interface, so a phone with Wi-Fi plus a VPN or hotspot hears the same host once
    // per interface. Showing it twice looks like two servers, and picking the VPN address would be the slow path.
    const mergeHosts = new Function(
      `${extractFunction(source, 'addressScore')}\n${extractFunction(source, 'mergeHosts')}\nreturn mergeHosts;`,
    )();
    const merged = mergeHosts([
      { id: 'aa', address: '26.42.62.124', port: 3000, rooms: [] },
      { id: 'aa', address: '192.168.1.23', port: 3000, rooms: [{ code: 'ABCD' }] },
    ]);
    assert.equal(merged.length, 1);
    assert.equal(merged[0].address, '192.168.1.23', 'the ordinary LAN address wins over the VPN one');
    assert.deepEqual(merged[0].others, ['26.42.62.124']);
    assert.deepEqual(merged[0].rooms, [{ code: 'ABCD' }], 'room data is kept even from the copy that lost');

    assert.equal(mergeHosts([{ id: 'aa', address: '192.168.1.1' }, { id: 'bb', address: '192.168.1.2' }]).length, 2);
    // Without an id (an older beacon) the address still has to group.
    assert.equal(mergeHosts([{ address: '192.168.1.1', port: 3000 }, { address: '192.168.1.1', port: 3000 }]).length, 1);
    assert.deepEqual(mergeHosts([null, undefined]), []);
  });

  test('a discovered room becomes a ?room= deep link', () => {
    const withRoom = new Function(`${extractFunction(source, 'withRoom')}\nreturn withRoom;`)();
    assert.equal(withRoom('http://192.168.1.23:3000/', 'ABCD'), 'http://192.168.1.23:3000/?room=ABCD');
    // It must survive the same normalisation a hand-typed address goes through.
    const DEFAULT_PORT = 3000;
    const normaliseAddress = new Function(
      'DEFAULT_PORT',
      `${extractFunction(source, 'normaliseAddress')}\nreturn normaliseAddress;`,
    )(DEFAULT_PORT);
    assert.equal(normaliseAddress(withRoom('http://192.168.1.23:3000/', 'ABCD')), 'http://192.168.1.23:3000/?room=ABCD');
    assert.equal(withRoom('not a url', 'ABCD'), 'not a url', 'a broken base URL must not throw');
  });

  test('the host name sent to the other phone comes from the device model', () => {
    // The extracted function closes over `navigator`, so bind it the same way the WebView does.
    const bindLabel = new Function('navigator', `${extractFunction(source, 'deviceLabel')}\nreturn deviceLabel;`);
    const label = (ua) => bindLabel({ userAgent: ua })();
    assert.equal(
      label('Mozilla/5.0 (Linux; Android 13; Pixel 7 Build/TQ3A.230805.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120 Mobile Safari/537.36'),
      'Pixel 7 的主机',
    );
    assert.equal(label('Mozilla/5.0 (Windows NT 10.0; Win64; x64)'), '卫戍协议主机');
    assert.equal(label(''), '卫戍协议主机');
    assert.ok(label('Mozilla/5.0 (Linux; Android 10; K) Mobile').length <= 40, 'the label is capped like the protocol caps it');
  });

  test('the host label reaches the Node side', () => {
    assert.match(source, /SP_HOST_NAME/, 'the Node entry point reads SP_HOST_NAME, so the launcher has to pass it');
  });
});

describe('android assembler: the beacon is shipped', { skip }, () => {
  const template = path.join(APP, 'scripts', 'nodejs-template');

  test('every beacon file lives in the template that gets copied into the APK', () => {
    for (const rel of ['lan/protocol.mjs', 'lan/net.mjs', 'lan/announce.mjs', 'lan/wire.mjs', 'lan/host.mjs']) {
      assert.ok(existsSync(path.join(template, rel)), `missing nodejs-template/${rel}`);
    }
  });

  test('the assembler copies the template recursively', () => {
    const script = readFileSync(path.join(APP, 'scripts', 'assemble-nodejs.mjs'), 'utf8');
    assert.match(script, /copyTemplate/, 'a flat readdir+copyFile would silently skip lan/');
  });

  test('the entry point hosts through the shared wiring, not a private copy of it', () => {
    const entry = readFileSync(path.join(template, 'index.js'), 'utf8');
    assert.match(entry, /import \{ startHost \} from '\.\/lan\/host\.mjs'/, 'lan-verify.mjs tests host.mjs, so index.js must use it too');
    assert.match(entry, /SP_HOST_NAME/);
  });

  test('a PC-hosted server announces the same way the app does', () => {
    // `npm start` on a PC is a completely silent server, so the phone has nothing to discover. host-with-lan.mjs is
    // the fix, and it has to keep using the APK's beacon module rather than its own copy of the wiring.
    const pcHost = path.join(APP, 'scripts', 'host-with-lan.mjs');
    assert.ok(existsSync(pcHost), 'missing android/scripts/host-with-lan.mjs');
    const source = readFileSync(pcHost, 'utf8');
    assert.match(source, /import \{ startServer, lanUrls \} from '\.\.\/\.\.\/server\/index\.js'/, 'it must import the original server, unmodified');
    assert.match(source, /import \{ announceServer \} from '\.\/nodejs-template\/lan\/wire\.mjs'/, 'the beacon wiring is shared with the APK');
    assert.match(source, /netsh advfirewall/, 'the firewall step is the next thing that fails after discovery works');

    // ...and the APK side uses the same helper, so the two cannot drift.
    const apkHost = readFileSync(path.join(template, 'lan', 'host.mjs'), 'utf8');
    assert.match(apkHost, /import \{ announceServer \} from '\.\/wire\.mjs'/);
    assert.match(readFileSync(path.join(template, 'lan', 'wire.mjs'), 'utf8'), /export function announceServer/);
  });

  test('the debug console switch is staged per build (DESIGN §21.34)', () => {
    // The template ships a token, the assembler stamps the value: one tree can be built as the release app (server
    // default) and another as the -Variant devtest app (forced on for every client).
    const entry = readFileSync(path.join(template, 'index.js'), 'utf8');
    assert.match(entry, /const consoleMode = '__SP_CONSOLE__';/, 'the template carries the token');
    assert.match(entry, /process\.env\.SP_CONSOLE = consoleMode;/, 'and applies it to the server it starts');
    assert.match(entry, /\(consoleMode === '0' \|\| consoleMode === '1'\)/, 'only 0/1 override the server default');
    assert.match(entry, /!process\.env\.SP_CONSOLE/, 'a platform-set SP_CONSOLE wins');

    const script = readFileSync(path.join(APP, 'scripts', 'assemble-nodejs.mjs'), 'utf8');
    assert.match(script, /--console=auto\|0\|1/);
    assert.match(script, /const CONSOLE = \['auto', '0', '1'\]\.includes\(consoleArg\) \? consoleArg : 'auto';/);
    assert.match(script, /split\(CONSOLE_TOKEN\)\.join\(CONSOLE\)/, 'the staged copy gets the value');

    const build = readFileSync(path.join(APP, 'scripts', 'build-apk.ps1'), 'utf8');
    assert.match(build, /\[ValidateSet\('release', 'devtest'\)\]\[string\]\$Variant = 'release'/, 'the variant switch');
    assert.match(build, /'assembleDevtest'/, 'the devtest task');
    assert.match(build, /--console=1/, 'devtest forces the console on');
    assert.match(build, /-dev-arm64\.apk/, 'its own artifact name');
    assert.match(build, /\$gameVersion = \(Get-Content/, 'the artifact name follows package.json, not a literal version');

    // the native project: the second build type, its application id suffix and its label overlay
    const gradle = readFileSync(path.join(APP, 'android', 'app', 'build.gradle'), 'utf8');
    assert.match(gradle, /devtest \{\n {12}initWith release\n {12}applicationIdSuffix "\.dev"\n {12}versionNameSuffix "-dev"/);
    const label = readFileSync(path.join(APP, 'android', 'app', 'src', 'devtest', 'res', 'values', 'strings.xml'), 'utf8');
    for (const name of ['app_name', 'title_activity_main']) assert.match(label, new RegExp(`<string name="${name}">卫戍协议：盟约·测试</string>`), name);
    assert.match(readFileSync(path.join(APP, 'android', 'app', 'src', 'main', 'res', 'values', 'strings.xml'), 'utf8'), /<string name="app_name">卫戍协议：盟约<\/string>/);
  });
});
